/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projekt_kon;

import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author Konrad
 */
public class GlowneOknoJPanel extends javax.swing.JPanel 
{
    private ArrayList <JButton> arButtony;
    
    /**
     * Creates new form NewJPanel
     */
    public GlowneOknoJPanel() 
    {
        initComponents();
        
        arButtony = new ArrayList<>();
        
        arButtony.add(jBtnBieg);
        arButtony.add(jBtnPlywanie);
        arButtony.add(jBtnPompki);
        arButtony.add(jBtnPrzysiady);
        arButtony.add(jBtnRower);
        arButtony.add(jBtnSkakanka);
    }

    public JButton GetBtnBieg()
    {
        return jBtnBieg;
    }
    
    public boolean CzyWcisnietyUzupelnijDziennik()
    {
        return !jTglBtnStatystyki.isSelected();
    }
    
    public ArrayList<JButton> GetCwiczeniaButtons()
    {
        return arButtony;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabTytul = new javax.swing.JLabel();
        jTglBtnUzupelnij = new javax.swing.JToggleButton();
        jTglBtnStatystyki = new javax.swing.JToggleButton();
        jBtnPlywanie = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jBtnSkakanka = new javax.swing.JButton();
        jBtnBieg = new javax.swing.JButton();
        jBtnPompki = new javax.swing.JButton();
        jBtnRower = new javax.swing.JButton();
        jBtnPrzysiady = new javax.swing.JButton();

        jLabTytul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabTytul.setText("Dziennik Treningowy");

        jTglBtnUzupelnij.setSelected(true);
        jTglBtnUzupelnij.setText("Uzupełnij Dziennik");
        jTglBtnUzupelnij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTglBtnUzupelnijActionPerformed(evt);
            }
        });

        jTglBtnStatystyki.setText("Statystyki");
        jTglBtnStatystyki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTglBtnStatystykiActionPerformed(evt);
            }
        });

        jBtnPlywanie.setText("Pływanie");

        jBtnSkakanka.setText("Skakanka");

        jBtnBieg.setText("Bieg");

        jBtnPompki.setText("Pompki");

        jBtnRower.setText("Rower");

        jBtnPrzysiady.setText("Przysiady");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabTytul)
                .addGap(99, 99, 99))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTglBtnUzupelnij, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTglBtnStatystyki, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnRower, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnPompki, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnPrzysiady, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnBieg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnPlywanie, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnSkakanka, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabTytul)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTglBtnUzupelnij, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTglBtnStatystyki, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnBieg, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPlywanie, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnSkakanka, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnPrzysiady, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPompki, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnRower, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTglBtnUzupelnijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTglBtnUzupelnijActionPerformed
        jTglBtnStatystyki.setSelected(false);
    }//GEN-LAST:event_jTglBtnUzupelnijActionPerformed

    private void jTglBtnStatystykiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTglBtnStatystykiActionPerformed
        jTglBtnUzupelnij.setSelected(false);
    }//GEN-LAST:event_jTglBtnStatystykiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBieg;
    private javax.swing.JButton jBtnPlywanie;
    private javax.swing.JButton jBtnPompki;
    private javax.swing.JButton jBtnPrzysiady;
    private javax.swing.JButton jBtnRower;
    private javax.swing.JButton jBtnSkakanka;
    private javax.swing.JLabel jLabTytul;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton jTglBtnStatystyki;
    private javax.swing.JToggleButton jTglBtnUzupelnij;
    // End of variables declaration//GEN-END:variables
}
