/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projekt_kon;

import java.util.Date;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Konrad
 */
public class StatystykiTabelaJPanel extends javax.swing.JPanel 
{
    Date DataOd;
    Date DataDo;
    /**
     * Creates new form UzupelnijDziennikJPanel
     */
    public StatystykiTabelaJPanel() 
    {
        initComponents();
    }

    public void SetNazwa(String A_Nazwa)
    {
        jLabNazwaCwiczenia.setText(A_Nazwa);
    }
    
    public void SetDaty(Date A_DataOd, Date A_DataDo)
    {
        DataOd = A_DataOd;
        DataDo = A_DataDo;
    }

    public void SetHeadery(String Header1, String Header2, String Header3)
    {
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        model.setColumnIdentifiers(new String[]{Header1, Header2, Header3});
    }
    
    public void DodajWiersz(Date data, String strData, String str1, String str2)
    {
        if(data.after(DataOd) && data.before(DataDo))
        {
            DefaultTableModel model = (DefaultTableModel) jTable.getModel();
            model.addRow(new String[]{strData, str1, str2});
        }
    }
    
    public void CzyscTabele()
    {
        try
        {
            DefaultTableModel dtm = (DefaultTableModel) jTable.getModel();
            dtm.setNumRows(0); 
        }
        catch(Exception e)
        {}
    }
    
    public JButton GetButtonWstecz()
    {
        return jBtnWstecz;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanelGorny = new java.awt.Panel();
        jLabNazwaCwiczenia = new javax.swing.JLabel();
        jLabStatystyki = new javax.swing.JLabel();
        jBtnWstecz = new javax.swing.JButton();
        jPanelDolny = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jPanelGorny.setBackground(new java.awt.Color(153, 204, 255));

        jLabNazwaCwiczenia.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabNazwaCwiczenia.setForeground(new java.awt.Color(255, 255, 255));
        jLabNazwaCwiczenia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabNazwaCwiczenia.setText("Bieg");

        jLabStatystyki.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabStatystyki.setForeground(new java.awt.Color(255, 255, 255));
        jLabStatystyki.setText("Statystyki Tabela");
        jLabStatystyki.setToolTipText("");

        jBtnWstecz.setText("Wstecz");
        jBtnWstecz.setMargin(new java.awt.Insets(2, 10, 2, 14));

        javax.swing.GroupLayout jPanelGornyLayout = new javax.swing.GroupLayout(jPanelGorny);
        jPanelGorny.setLayout(jPanelGornyLayout);
        jPanelGornyLayout.setHorizontalGroup(
            jPanelGornyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGornyLayout.createSequentialGroup()
                .addComponent(jLabStatystyki)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabNazwaCwiczenia, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jBtnWstecz))
        );
        jPanelGornyLayout.setVerticalGroup(
            jPanelGornyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGornyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabNazwaCwiczenia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
            .addGroup(jPanelGornyLayout.createSequentialGroup()
                .addGroup(jPanelGornyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabStatystyki)
                    .addComponent(jBtnWstecz))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelDolny.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelDolnyLayout = new javax.swing.GroupLayout(jPanelDolny);
        jPanelDolny.setLayout(jPanelDolnyLayout);
        jPanelDolnyLayout.setHorizontalGroup(
            jPanelDolnyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDolnyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelDolnyLayout.setVerticalGroup(
            jPanelDolnyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDolnyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGorny, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelDolny, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelGorny, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelDolny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnWstecz;
    private javax.swing.JLabel jLabNazwaCwiczenia;
    private javax.swing.JLabel jLabStatystyki;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelDolny;
    private java.awt.Panel jPanelGorny;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
